// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

var coldStart = Css.style(/* :: */[
      Css.fontFamily("'Space Mono', monospace"),
      /* :: */[
        Css.fontSize(Css.rem(1.5)),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* coldStart */coldStart];

function str(prim) {
  return prim;
}

function ColdStart(Props) {
  return React.createElement("h1", {
              className: coldStart
            }, "The deployed server is a CodeSandbox.io instance booting from a cold start. Wait ~30 seconds after executing your first query to see results. After that, you should see updates instantly!");
}

var make = ColdStart;

exports.Styles = Styles;
exports.str = str;
exports.make = make;
/* coldStart Not a pure module */
